import re
import json
from pathlib import Path

BASE_PATH = Path(__file__).parent

# 1. 原神角色 (Genshin Impact)
genshin_char = {
    "furina": [r"furina (genshin impact)", "girl, white hair"],
    "aether": [r"aether (genshin impact)", "boy, blonde hair"],
    "sora": [r"aether (genshin impact)", "boy, blonde hair"],
    "shota aether": [r"aether (genshin impact), {{aged down}}, shota, ", "boy, blonde hair"],
    "kong": [r"aether (genshin impact)", "boy, blonde hair"],
    "paimon": [r"paimon (genshin impact)", "girl, white hair"],
    # "main boy": [r"aether (genshin impact)", "boy, blonde hair"],
    "hu tao": [r"hu tao (genshin impact)", "girl, brown hair"],
    "nahida": [r"nahida (genshin impact)", "girl, white hair"],
    "baizhu": [r"baizhu (genshin impact)", "man, green hair"],
    "hutao": [r"hu tao (genshin impact)", "girl, brown hair"],
    "qiqi": [r"qiqi (genshin impact)", "girl, purple hair"],
    "columbina": [r"columbina (genshin impact)", "girl, black hair"],
    "columbia": [r"columbina (genshin impact)", "girl, black hair"],
    # "columbina": [r"black hair, multicolored hair, hair ornament, white dress", "girl, black hair", "reference\\genshin\\columbina.png"],
    # "columbia": [r"black hair, multicolored hair, hair ornament, white dress", "girl, black hair", "reference\\genshin\\columbina.png"],
    # "sandrone": [r"sandrone (genshin impact)", "girl, brown hair"],
    "sandrone": [r"headdress, brown hair, sandrone (genshin impact)", "girl, brown hair", "reference\\genshin\\sandrone.png"],
    "albedo": [r"albedo (genshin impact)", "boy, blonde hair"],
    "arlecchino": [r"arlecchino (genshin impact)", "girl, white hair"],
    "chongyun": [r"chongyun (genshin impact)", "boy, blue hair"],
    "guoba": [r"guoba (genshin impact)", "small creature"],
    "wanjia": [r"lumine (genshin impact)", "girl, blonde hair"],
    "lumine": [r"lumine (genshin impact)", "girl, blonde hair"],
    "traveler": [r"lumine (genshin impact)", "girl, blonde hair"],
    "ningguang": [r"ningguang (genshin impact)", "girl, white hair"],
    "tartaglia": [r"tartaglia (genshin impact)", "boy, orange hair"],
    "xiangling": [r"xiangling (genshin impact)", "girl, blue hair"],
    "xingqiu": [r"xingqiu (genshin impact)", "boy, blue hair"],
    "yelan": [r"yelan (genshin impact)", "girl, black hair"],
    "zhongli": [r"zhongli (genshin impact)", "man, brown hair"],
    "shenhe": [r"shenhe (genshin impact)", "girl, white hair"],
    "xianyun": [r"xianyun (genshin impact)", "girl, dark hair"],
    "xian yun": [r"xianyun (genshin impact)", "girl, dark hair"],
    "arataki itto": [r"arataki itto (genshin impact)", "man, white hair"],
    "jean": [r"jean (genshin impact)", "girl, blonde hair"],
    "klee": [r"klee (genshin impact)", "girl, blonde hair"],
    "mavuika": [r"mavuika (genshin impact)", "girl, red hair"],
    "neuvillette": [r"neuvillette (genshin impact)", "man, blue hair"],
    "raiden shogun": [r"raiden shogun", "girl, purple hair"],
    "raiden ei": [r"raiden shogun", "girl, purple hair"],
    "ei": [r"raiden shogun", "girl, purple hair"],
    "venti": [r"venti (genshin impact)", "boy, green hair"],
    "keqing": [r"keqing (genshin impact)", "girl, purple hair"],
    "keqing alter": [r"keqing (opulent splendor) (genshin impact) ", "girl, purple hair"],
    "ganyu": [r"ganyu (genshin impact)", "girl, blue hair"],
    "ganyu alter": [r"ganyu (twilight blossom) (genshin impact)", "girl, blue hair"],
    "yaoyao": [r"yaoyao (genshin impact)", "girl, brown hair"],
    "citlali": [r"citlali (genshin impact)", "girl, pink hair"],
    "obsidian grandma": [r"citlali (genshin impact)", "girl, pink hair"],
    "kachina": [r"kachina (genshin impact)", "girl, grey hair"],
    "ororon": [r"ororon (genshin impact)", "man, dark hair"],
    "olorun": [r"ororon (genshin impact)", "man, dark hair"],
    "kinich": [r"kinich (genshin impact)", "boy, black hair"],
    "yun jin": [r"yun jin (genshin impact)", "girl, black hair"],
    "yunjin": [r"yun jin (genshin impact)", "girl, black hair"],
    "noelle": [r"noelle (genshin impact)", "girl, white hair"],
    "yae miko": [r"yae miko", "girl, pink hair"],
    "focalors": [r"focalors (genshin impact)", "girl, white hair"],
    "xiao": [r"xiao (genshin impact)", "boy, dark hair"],
    "diluc": [r"diluc (genshin impact)", "man, red hair"],
    "ifa": [r"ifa (genshin impact)", "boy, white hair"],
    "kaeya": [r"kaeya (genshin impact)", "man, dark hair"],
    "wanderer": [r"wanderer (genshin impact)", "boy, dark hair"],
    "scaramouche": [r"scaramouche (genshin impact)", "boy, dark hair"],
    "barbara": [r"barbara (genshin impact)", "girl, blonde hair"],
    "amber": [r"amber (genshin impact)", "girl, brown hair"],
    "bennett": [r"bennett (genshin impact)", "boy, white hair"],
    "fischl": [r"fischl (genshin impact)", "girl, blonde hair"],
    "fischl alter": [r"fischl (ein immernachtstraum) (genshin impact) ", "girl, blonde hair"],
    "eula": [r"eula (genshin impact)", "girl, blue hair"],
    "lisa": [r"lisa (genshin impact)", "girl, brown hair"],
    "sucrose": [r"sucrose (genshin impact)", "girl, green hair"],
    "oz": [r"oz (genshin impact)", "bird, purple bird"],
    "dainsleif": [r"dainsleif (genshin impact)", "man, blonde hair"],
    "kaedehara kazuha": [r"kaedehara kazuha", "boy, grey hair"],
    "kazuha": [r"kaedehara kazuha", "boy, grey hair"],
    "shikanoin heizou": [r"shikanoin heizou", "boy, red hair"],
    "collei": [r"collei (genshin impact)", "girl, green hair"],
    "tighnari": [r"tighnari (genshin impact)", "man, dark hair"],
    "cyno": [r"cyno (genshin impact)", "man, white hair"],
    "flora": [r"flora (genshin impact)", "girl, brown hair"],
    "katheryne": [r"katheryne (genshin impact)", "girl, black hair"],
    "sara": [r"sara (genshin impact)", "girl, brown hair"],
    "yoimiya": [r"yoimiya (genshin impact)", "girl, brown hair"],
    "beidou": [r"beidou (genshin impact)", "woman, black hair"],
    "kuki shinobu": [r"kuki shinobu", "girl, green hair"],
    "mona": [r"mona (genshin impact)", "girl, purple hair"],
    "xinyan": [r"xinyan (genshin impact)", "girl, purple hair"],
    "makoto": [r"makoto (genshin impact)", "girl, purple hair"],
    "durin": [r"durin (genshin impact), purple hair, dragon boy", "boy, purple hair", "reference\\genshin\\durin.png"],
    "diona": [r"diona (genshin impact)", "girl, pink hair"],
    "kujou sara": [r"kujou sara (genshin impact)", "girl, black hair"],
    "clorinde": [r"clorinde (genshin impact)", "girl, purple hair"],
    "navia": [r"navia (genshin impact)", "girl, blonde hair"],
    "candace": [r"candace (genshin impact)", "woman, dark hair"],
    "dehya": [r"dehya (genshin impact)", "woman, brown hair"],
    "yanfei": [r"yanfei (genshin impact)", "girl, pink hair"],
    "chevreuse": [r"chevreuse (genshin impact)", "girl, purple hair"],
    "chiori": [r"chiori (genshin impact)", "girl, dark hair"],
    "ayaka": [r"kamisato ayaka", "girl, white hair"],
    "ayaka alter": [r"kamisato ayaka (springbloom missive)", "girl, white hair"],
    "kamisato ayaka": [r"kamisato ayaka", "girl, white hair"],
    "kamisato ayato": [r"kamisato ayato", "boy, white hair"],
    "ayato": [r"kamisato ayato", "boy, white hair"],
    "spring ayaka": [r"kamisato ayaka (springbloom missive)", "girl, white hair"],
    "tsaritsa": [r"tsaritsa (genshin impact)", "woman, blue hair"],
    "xilonen": [r"xilonen (genshin impact)", "girl, blonde hair"],
    "sangonomiya kokomi": [r"sangonomiya kokomi", "girl, pink hair"],
    "kokomi": [r"sangonomiya kokomi", "girl, pink hair"],
    "faruzan": [r"faruzan (genshin impact)", "girl, blue hair"],
    "cloud retainer": [r"cloud retainer (genshin impact)", "bird"],
    "rosaria": [r"rosaria (genshin impact)", "woman, purple hair"],
    "mualani": [r"mualani (genshin impact)", "girl, white hair"],
    "escoffier": [r"escoffier (genshin impact)", "girl, orange hair"],
    "aikefei": [r"escoffier (genshin impact)", "girl, orange hair"],
    "aekhphi": [r"escoffier (genshin impact)", "girl, orange hair"],
    "varesa": [r"varesa (genshin impact)", "girl, pink hair, horn"],
    "skirk": [r"skirk (genshin impact)", "girl, grey hair"],
    "cacucu": [r"cacucu (genshin impact)", "bird, pink bird"],
    "layla": [r"layla (genshin impact)", "girl, blue hair"],
    "lynette": [r"lynette (genshin impact)", "girl, grey hair"],
    "lyney": [r"lyney (genshin impact)", "boy, grey hair"],
    "kirara": [r"kirara (genshin impact)", "girl, grey hair, animal ears"],
    "thoma": [r"thoma (genshin impact)", "boy, blonde hair"],
    "tubby": [r"tubby (genshin impact)", "bird, hat"],
    "sigewinne": [r"sigewinne (genshin impact)", "girl, blue hair"],
    "rukkhadevata": [r"rukkhadevata (genshin impact)", "girl, white hair"],
    "greater lord rukkhadevata": [r"rukkhadevata (genshin impact)", "girl, white hair"],
    "buer": [r"rukkhadevata (genshin impact)", "girl, white hair"],
    "taroumaru": [r"taroumaru (genshin impact)", "dog, orange dog"],
    "charlotte": [r"charlotte (genshin impact)", "girl, pink hair"],
    "gorou": [r"gorou (genshin impact)", "boy, brown hair, animal ears"],
    "nilou": [r"nilou (genshin impact)", "girl, red hair"],
    "nilou alter": [r"nilou (breeze of sabaa) (genshin impact)", "girl, red hair"],
    "ioroi": [r"ioroi (genshin impact)", "animal"],
    "sayu": [r"sayu (genshin impact)", "girl, green hair"],
    "alhaitham": [r"alhaitham (genshin impact)", "boy, grey hair"],
    "asmoday": [r"asmoday (genshin impact)", "girl, white hair"],
    "unknown god": [r"asmoday (genshin impact)", "girl, white hair"],
    "sustainer of heavenly principles": [r"asmoday (genshin impact)", "girl, white hair"],
    "abyss mage": [r"abyss mage (genshin impact)", "monster"],
    "slime": [r"slime (genshin impact)", "monster"],
    "hilichurl": [r"hilichurl (genshin impact)", "monster"],
    "yuegui": [r"yuegui (genshin impact) ", "yellow toy"],
    "madame ping": [r" {{old woman}}, madame ping (genshin impact), ", "old woman"],
    "aino": [r"pink hair, hair ornament, loli", "girl, pink hair", "reference\\genshin\\aino.png"],
    "flins": [r"blue hair", "man, blue hair", "reference\\genshin\\flins.png"],
    "illuga": [r"grey hair, shirt", "boy, grey hair", "reference\\genshin\\illuga.png"],
    "ineffa": [r"blue hair, robot joints", "girl, blue hair", "reference\\genshin\\ineffa.png"],
    "jahoda": [r"blonde hair, eyewear on head, hat", "girl, blonde hair", "reference\\genshin\\jahoda.png"],
    "yakeda": [r"blonde hair, eyewear on head, hat", "girl, blonde hair", "reference\\genshin\\jahoda.png"],
    "lauma": [r"pointy ears, purple hair, antlers", "girl, purple hair", "reference\\genshin\\lauma.png"],
    "nefer": [r"green hair, jewelry", "girl, green hair", "reference\\genshin\\nefer.png"],
    "varka": [r"blonde hair", "man, blonde hair", "reference\\genshin\\varka.png"],
    "linnea": [r"pink hair, hair ornament", "girl, pink hair", "reference\\genshin\\linnea.png"],
    "zibai": [r"white hair, ponytail, thighhighs", "girl, white hair", "reference\\genshin\\zibai.png"],
    "nico": [r"blonde hair, hat, white pantyhose", "girl, blonde hair", "reference\\genshin\\nico.png"],
    "bulunni": [r"purple hair, loli", "girl, purple hair", "reference\\genshin\\bulunni.png"],
    "alice": [r"blonde hair, pointy ears", "girl, blonde hair", "reference\\genshin\\alice.png"],
    "lanyan": [r"black hair, hair ornament", "girl, black hair", "reference\\genshin\\lanyan.jpg"],
    "wriothesley": [r"wriothesley (genshin impact)", "girl, black hair", "reference\\genshin\\lanyan.jpg"],
}

# 2. 星穹铁道角色 (Honkai: Star Rail)
starrail_char = {
    "yunli": [r"yunli (honkai: star rail)", "girl, dark hair"],
    "feixiao": [r"feixiao (honkai: star rail)", "girl, white hair"],
    "jing yuan": [r"jing yuan", "man, white hair"], 
    "yanqing": [r"yanqing (honkai: star rail)", "boy, blonde hair"],
    "sparkle": [r"sparkle (honkai: star rail)", "girl, black hair"],
    "caelus": [r"caelus (honkai: star rail)", "boy, grey hair"],
    "trailblazer (male)": [r"caelus (honkai: star rail)", "boy, grey hair"],
    "male_protagonist": [r"caelus (honkai: star rail)", "boy, grey hair"],
    "protagonist": [r"caelus (honkai: star rail)", "boy, grey hair"],
    "qiong": [r"caelus (honkai: star rail)", "boy, grey hair"],
    "caelum": [r"caelus (honkai: star rail)", "boy, grey hair"],
    "stelle": [r"stelle (honkai: star rail)", "girl, grey hair"],
    "xing": [r"stelle (honkai: star rail)", "girl, grey hair"],
    "firefly": [r"firefly (honkai: star rail)", "girl, white hair, hair band"],
    "firefly spring": [r"firefly (honkai: star rail)", "girl, white hair, hair band"],
    "trailblazer": [r"caelus (honkai: star rail)", "boy, grey hair"],
    "fu xuan": [r"fu xuan (honkai: star rail)", "girl, pink hair"],
    "fuxuan": [r"fu xuan (honkai: star rail)", "girl, pink hair"],
    "march 7th": [r"march 7th (honkai: star rail)", "girl, pink hair"],
    "sanyue": [r"march 7th (honkai: star rail)", "girl, pink hair"],
    "kafka": [r"kafka (honkai: star rail)", "  girl, purple hair"],
    "robin": [r"robin (honkai: star rail)", "girl, blue hair"],
    "sam": [r"sam (honkai: star rail)", "robot face"],
    "silver wolf": [r"silver wolf (honkai: star rail)", "girl, silver hair"],
    "silverwolf": [r"silver wolf (honkai: star rail)", "girl, silver hair"],
    "tingyun": [r"tingyun (honkai: star rail)", "girl, brown hair"],
    "ting yun": [r"tingyun (honkai: star rail)", "girl, brown hair"],
    "qingque": [r"qingque (honkai: star rail)", "girl, brown hair, hair clip"],
    "qing que": [r"qingque (honkai: star rail)", "girl, brown hair, hair clip"],
    "aventurine": [r"aventurine (honkai: star rail)", "boy, blonde hair"],
    "clara (honkai: star rail)": [r"clara (honkai: star rail)", "girl, white hair"],
    "clara": [r"clara (honkai: star rail)", "girl, white hair"],
    "owlbert": [r"owlbert (honkai: star rail)", "bird, white bird"],
    "natasha": [r"natasha (honkai: star rail)", "girl, dark hair"],
    "sampo koski": [r"sampo koski (honkai: star rail)", "man, purple hair"],
    "sampo": [r"sampo koski (honkai: star rail)", "man, purple hair"],
    "svarog": [r"svarog (honkai: star rail)", "robot face"],
    "bronya rand": [r"bronya rand", "girl, grey hair"],
    "starrail bronya": [r"bronya rand", "girl, grey hair"],
    "hook": [r"hook (honkai: star rail)", "girl, yellow hair"],
    "pela": [r"pela (honkai: star rail)", "girl, purple hair"],
    "starrail seele": [r"seele (honkai: star rail)", "girl, purple hair"],
    "dan heng": [r"dan heng (honkai: star rail)", "boy, black hair"],
    "danheng": [r"dan heng (honkai: star rail)", "boy, black hair"],
    "starrail himeko": [r"himeko (honkai: star rail)", "girl, red hair"],
    "pom-pom": [r"pom-pom (honkai: star rail)", "toy, hat"],
    "welt yang": [r"welt yang", "man, brown hair"],
    "welt": [r"welt yang", "man, brown hair"],
    "hanya": [r"hanya (honkai: star rail)", "girl, grey hair, horns"],
    "hannya": [r"hanya (honkai: star rail)", "girl, grey hair, horns"],
    "bailu": [r"bailu (honkai: star rail)", "girl, purple hair, antlers"],
    "blade": [r"blade (honkai: star rail)", "man, dark hair"],
    "jade": [r"jade (honkai: star rail)", "girl, pink hair"],
    "sunday": [r"sunday (honkai: star rail)", "man, grey hair"],
    "xipe": [r"xipe (honkai: star rail)", "girl, purple skin"],
    "huohuo": [r"huohuo (honkai: star rail)", "girl, green hair"],
    "tail": [r"tail (honkai: star rail)", "green animal"],
    "sushang": [r"sushang (honkai: star rail)", "girl, brown hair"],
    "suishang": [r"sushang (honkai: star rail)", "girl, brown hair"],
    "fugue": [r"fugue (honkai: star rail)", "girl, black hair, fox ears"],
    "lingsha": [r"lingsha (honkai: star rail)", "girl, brown hair"],
    "luocha": [r"luocha (honkai: star rail)", "boy, blonde hair"],
    "yukong": [r"yukong (honkai: star rail)", "girl, green hair, fox ears"],
    "jingliu": [r"jingliu (honkai: star rail)", "girl, white hair"],
    "topaz": [r"topaz (honkai: star rail)", "girl, white hair"],
    "herta": [r"herta (honkai: star rail)", "girl, brown hair"],
    "asta": [r"asta (honkai: star rail)", "girl, pink hair"],
    "xueyi": [r"xueyi (honkai: star rail)", "girl, black hair"],
    "ruan mei": [r"ruan mei (honkai: star rail)", "girl, black hair"],
    "guinaifen": [r"guinaifen (honkai: star rail)", "girl, orange hair"],
    "guinafen": [r"guinaifen (honkai: star rail)", "girl, orange hair"],
    "peppy": [r"peppy (honkai: star rail)", "dog, white dog"],
    "jiaoqiu": [r"jiaoqiu (honkai: star rail)", "boy, pink hair"],
    "huaiyan": [r"old man, white hair, short hair", "old man, white hair"],
    "qingni": [r"npc, waitress, black hair, bobcut", "waitress, black hair"],
    "acheron": [r"acheron (honkai: star rail)", "girl, purple hair"],
    "huangquan": [r"acheron (honkai: star rail)", "girl, purple hair"],
    "lynx": [r"lynx landau)", "girl, golden hair, animal ears"],
    "serval": [r"serval landau)", "girl, golden hair, choker"],
    "gepard": [r"gepard landau)", "boy, golden hair"],


    "black swan": [r"black swan (honkai: star rail), ", "girl, purple hair"],
    "arlan": [r"arlan (honkai: star rail)", "boy, grey hair"],
    "aglaea": [r"aglaea (honkai: star rail), blonde hair", "girl, blonde hair", "reference\\starrail\\aglaea.jpg"],
    "aglaia": [r"aglaea (honkai: star rail), blonde hair", "girl, blonde hair", "reference\\starrail\\aglaea.jpg"],
    "anaxa": [r"anaxa (honkai: star rail), green hair", "girl, green hair", "reference\\starrail\\anaxa.jpg"],
    "castorice": [r"castorice (honkai: star rail), purple hair", "girl, purple hair", "reference\\starrail\\castorice.jpg"],
    "xiadie": [r"castorice (honkai: star rail), purple hair", "girl, purple hair", "reference\\starrail\\castorice.jpg"],
    "xadie": [r"castorice (honkai: star rail), purple hair", "girl, purple hair", "reference\\starrail\\castorice.jpg"],
    "cerydra": [r"blue hair, crown", "girl, blue hair", "reference\\starrail\\cerydra.jpg"],
    "cipher": [r"cipher (honkai: star rail), grey hair", "girl, grey hair", "reference\\starrail\\cipher.jpg"],
    "saifeier": [r"cipher (honkai: star rail), grey hair", "girl, grey hair", "reference\\starrail\\cipher.jpg"],
    "cyrene": [r"pink hair, long hair, hair flower", "girl, pink hair", "reference\\starrail\\cyrene.png"],
    "xilian": [r"pink hair, long hair, hair flower", "girl, pink hair", "reference\\starrail\\cyrene.png"],
    "evernight": [r"pink hair, hair ornament, black dress", "girl, pink hair", "reference\\starrail\\evernight.png"],
    "changyeyue": [r"pink hair, hair ornament, black dress", "girl, pink hair", "reference\\starrail\\evernight.png"],
    "dark march": [r"pink hair, hair ornament, black dress", "girl, pink hair", "reference\\starrail\\evernight.png"],
    "hyacine": [r"hyacine (honkai: star rail), pink hair", "girl, pink hair", "reference\\starrail\\hyacine.jpg"],
    "fengjin": [r"hyacine (honkai: star rail), pink hair", "girl, pink hair", "reference\\starrail\\hyacine.jpg"],
    "hysilens": [r"black hair, hair ornament", "girl, black hair", "reference\\starrail\\hysilens.jpg"],
    "mydei": [r"mydei (honkai: star rail)", "boy, red hair", "reference\\starrail\\mydei.jpg"],
    "phainon": [r"phainon (honkai: star rail), white hair", "boy, white hair", "reference\\starrail\\phainon.jpg"],
    "saber": [r"blonde hair", "girl, blonde hair", "reference\\starrail\\saber.jpg"],
    "sparxie": [r"white hair, twin tails", "girl, white hair", "reference\\starrail\\sparxie.png"],
    "huohua": [r"white hair, twin tails", "girl, white hair", "reference\\starrail\\sparxie.png"],
    "huo hua": [r"white hair, twin tails", "girl, white hair", "reference\\starrail\\sparxie.png"],
    "the dahlia": [r"black hair, hat", "girl, black hair", "reference\\starrail\\the dahlia.png"],
    "tribbie": [r"red hair, loli", "girl, red hair", "reference\\starrail\\tribbie.jpg"],
    "yao guang": [r"white hair, hair ornament", "girl, white hair", "reference\\starrail\\yao guang.png"],
    "yaoguang": [r"white hair, hair ornament", "girl, white hair", "reference\\starrail\\yao guang.png"],
    "feiying": [r"pink hair, hair flower", "girl, pink hair", "reference\\starrail\\feiying.png"],
    "pearl": [r"brown hair, head fins, forehead jewel", "girl, brown hair", "reference\\starrail\\pearl.png"],
}

zzz_character = {
    "wise": [r"wise (zenless zone zero)", "boy, grey hair"],
    "zhe": [r"wise (zenless zone zero)", "boy, grey hair"],
    "belle": [r"belle (zenless zone zero)", "girl, purple hair"],
    "rina": [r"belle (zenless zone zero)", "girl, purple hair"],
    "soukaku rin": [r"belle (zenless zone zero)", "girl, purple hair"],
    "hoshimi miyabi": [r"hoshimi miyabi", "girl, black hair, fox ears"],
    "miyabi": [r"hoshimi miyabi", "girl, black hair, fox ears"],
    "aria": [r"pink hair, twin tails", "girl, pink hair", "reference\\zzz\\Aria.png"],
    "seed": [r"blue hair, robot girl", "girl, blue hair", "reference\\zzz\\Seed.png"],
    "vivian": [r"vivian (zenless zone zero)", "girl,light purple hair"],
    "vivian banshee": [r"vivian (zenless zone zero)", "girl,light purple hair"],
    "eous": [r"eous (zenless zone zero)", "bunny"],
    "yi'erse": [r"eous (zenless zone zero)", "bunny"],
    "bangboo": [r"eous (zenless zone zero)", "bunny"],
    "hugo": [r"ugo vlad", "boy, blonde hair"],
    "hugo vlad": [r"ugo vlad", "boy, blonde hair"],
    "corin": [r"corin wickes", "girl, green hair"],
    # "nicole": [r"nicole demara", "girl, pink hair"],
    "nicole demara": [r"nicole demara", "girl, pink hair"],
    "anby": [r"anby demara", "girl, grey hair"],
    "billy": [r"billy kid", "boy, white hair"],
    "zhu yuan": [r"{{zhu yuan}}, zenless zone zero, police woman", "girl, black hair"],
    "yi xuan": [r"white hair, single hair intake, hair pin", "girl, white hair", "reference\\zzz\\Yixuan.png"],
    "yixuan": [r"white hair, single hair intake, hair pin", "girl, white hair", "reference\\zzz\\Yixuan.png"],
    "ju fufu": [r"blonde hair, tiger girl", "girl, blonde hair", "reference\\zzz\\Ju Fufu.png"],
    "lucia": [r"blue hair,horns", "girl, blue hair", "reference\\zzz\\Lucia Elowen.png"],
    "dialyn": [r"braided twintails,panda hair ornament,split-color hair", "girl, white hair", "reference\\zzz\\Dialyn.png"],
    "ye shunguang": [r"brown hair, droopy ears", "girl, brown hair", "reference\\zzz\\Ye Shunguang.png"],
    "zhao": [r"pink fur, furry female, rabbit girl", "girl, furry female, pink fur", "reference\\zzz\\Zhao.png"],
    "sunna": [r"green hair, multiple hair clips ", "girl, green hair", "reference\\zzz\\Sunna.png"],
    "nangong yu": [r"black hair, multiple hair clips", "girl, black hair", "reference\\zzz\\Nangong Yu.png"],
    "liu": [r"pink hair", "girl, pink hair", "reference\\zzz\\Liu.png"],
}

mc_character = {
    "female rover": [r"female rover (wuthering waves)", "girl, black hair"],
    "male rover": [r"male rover (wuthering waves)", "boy, black hair"],
    "rover": [r"male rover (wuthering waves)", "boy, black hair"],
    "phoebe": [r"phoebe (wuthering waves)", "girl, blonde hair"],
    "carlotta": [r"carlotta (wuthering waves)", "girl, white hair"],
    "koleda": [r"carlotta (wuthering waves)", "girl, white hair"],
    "cartethyia": [r"cartethyia (wuthering waves)", "girl, blonde hair"],
    "cathesia": [r"cartethyia (wuthering waves)", "girl, blonde hair"],
    "katisia": [r"cartethyia (wuthering waves)", "girl, blonde hair"],
    "katixiya": [r"cartethyia (wuthering waves)", "girl, blonde hair"],
    "katishia": [r"cartethyia (wuthering waves)", "girl, blonde hair"],
    "cantarella": [r"cantarella (wuthering waves)", "girl, purple hair"],
    "cantrella": [r"cantarella (wuthering waves)", "girl, purple hair"],
    "fleurdelys": [r"fleurdelys (wuthering waves)", "girl, blonde hair"],
    "shorekeeper": [r"shorekeeper (wuthering waves)", "girl, blue hair"],
    "iuno": [r" iuno (wuthering waves)", "girl, blue hair"],
    "yuno": [r" iuno (wuthering waves)", "girl, blue hair"],
    "camellya": [r"camellya (wuthering waves)", "girl, white hair"],
    "encore": [r"encore (wuthering waves)", "girl, pink hair"],
    "jinhsi": [r"jinhsi (wuthering waves)", "girl, white hair"],
    "changli": [r"changli (wuthering waves)", "girl, red hair"],
    "sanhua": [r"sanhua (wuthering waves)", "girl, white hair"],
    "zani": [r"zani (wuthering waves)", "girl, white hair"],
    "abby": [r"abby (wuthering waves)", "dog"],
    "abu": [r"abby (wuthering waves)", "dog"],
    "verina": [r"verina (wuthering waves)", "girl, blonde hair"],
    "roccia": [r"roccia (wuthering waves)", "girl, blue hair"],
    "yinlin": [r"yinlin (wuthering waves)", "girl, red hair"],
    "feixue": [r"white hair, miko, ponytail", "girl, white hair", "reference\\mc\\feixue.png"],
}

arknights_character = {
    "platinum": [r"platinum (arknights)", "girl, white hair"],
    "hortensia": [r"platinum (arknights)", "girl, white hair"],
    "kal'tsit": [r"kal'tsit (arknights)", "girl, white hair"],
    "amiya": [r"amiya (arknights) ", "girl, black hair"],
    "skadi": [r"skadi the corrupting heart (arknights)", "girl, white hair"],
    "specter": [r"specter (arknights)", "girl, white hair"],
    "black specter": [r"specter the unchained (arknights)", "girl, white hair"],
    "dusk": [r"dusk (arknights)", "girl, black hair, antlers"],
    "xi": [r"dusk (arknights)", "girl, black hair, antlers"],
    "nian": [r"nian (arknights)", "girl, white hair, antlers"],
    "shu": [r"shu (arknights)", "girl, blonde hair, antlers"],
    "spring shu": [r"shu (spring feast) (arknights)", "girl, blonde hair, antlers"],
    "ling": [r"ling (arknights)", "girl, blue hair, antlers"],
    "doctor": [r"doctor (arknights), white hair", "boy, white hair"],
    "shamare": [r"shamare (arknights)", "girl, purple hair"],
    "suzuran": [r"suzuran (arknights)", "girl, blonde hair, animal ears"],
    "sussurro": [r"sussurro (arknights)", "girl, brown hair"],
    "myrtle": [r"myrtle (arknights)", "girl, brown hair"],
    "astesia": [r"astesia (arknights)", "girl, black hair"],
    "astgenne": [r"astgenne (arknights)", "girl, black hair"],
    "platinum": [r"platinum (arknights)", "girl, grey hair"],
    "beanstalk": [r"beanstalk (arknights)", "girl, white hair"],
    "la pluma": [r"la pluma (arknights)", "girl, black hair"],
    "nine-colored deer": [r"nine-colored deer (arknights)", "girl, white hair, antlers"],
    "muelsyse": [r"muelsyse (arknights)", "girl, brown hair"],
    "mousse": [r"muelsyse (arknights)", "girl, grey hair"],
    "vulpisfoglia": [r"vulpisfoglia (arknights)", "girl, blonde hair"],
    "mon3tr": [r"mon3tr (arknights)", "girl, black hair"],
    "haruka": [r"haruka (arknights)", "girl, red hair"],
    "momoka": [r"haruka (arknights)", "girl, red hair"],
    "dorothy": [r"dorothy (arknights)", "girl, blonde hair, animal ears"],
    "exusiai": [r"exusiai (arknights)", "girl, red hair"],
    "archetto": [r"archetto (arknights)", "girl, orange hair"],
    "saileach": [r"saileach (arknights)", "girl, golden hair, horns"],
    "vigna": [r"vigna (arknights)", "girl, red hair"],
    "horn": [r"horn (arknights)", "girl, brown hair"],
    "flametail": [r"flametail (arknights)", "girl, red hair"],
    "ashlock": [r"ashlock (arknights)", "girl, grey hair"],
    "fartooth": [r"fartooth (arknights)", "girl, grey hair"],
    "greyy": [r"greyy (arknights)", "boy, brown hair"],
    "schwarz": [r"schwarz (arknights)", "girl, grey hair"],
    "irene": [r" irene (arknights) ", "girl, grey hair"],



    "chen": [r"chen (arknights)", "woman, black hair, horns"],
    "ch'en": [r"chen (arknights)", "woman, black hair, horns"],
    "chen alter": [r"chen the holungday (arknights)", "woman, black hair"],
    "hoshiguma": [r"hoshiguma (arknights)", "woman, green hair, horns"],
    "liskarm": [r"liskarm (arknights)", "girl, white hair, horns"],
    "franka": [r"franka (arknights)", "girl, brown hair"],
    "swire": [r"swire (arknights)", "girl, blonde hair"],
    "lin": [r"lin (arknights)", "woman, black hair"],

    # ===== 龙门 / 近卫 =====
    "bagpipe": [r"bagpipe (arknights)", "girl, orange hair"],
    "siege": [r"siege (arknights)", "woman, blonde hair"],
    "vigna": [r"vigna (arknights)", "girl, red hair, horns"],
    "reed": [r"reed (arknights)", "girl, grey hair, horns"],
    "necrass": [r"necrass (arknights)", "girl, grey hair, horns"],
    "reed alter": [r"reed the flame shadow (arknights)", "girl, grey hair, horns"],

    # ===== 狙击 =====
    "exusiai": [r"exusiai (arknights)", "girl, red hair"],
    "blue poison": [r"blue poison (arknights)", "girl, pink hair"],
    "meteorite": [r"meteorite (arknights)", "woman, brown hair"],
    "fiammetta": [r"fiammetta (arknights)", "woman, red hair"],
    # ===== 术师 =====
    "ifrit": [r"ifrit (arknights)", "girl, grey hair, horns"],
    "eyjafjalla": [r"eyjafjalla (arknights)", "girl, brown hair, horns"],
    "goldenglow": [r"goldenglow (arknights)", "girl, pink hair"],
    "ceobe": [r"ceobe (arknights)", "girl, blonde hair, horns"],

    # ===== 医疗 =====
    "shining": [r"shining (arknights)", "woman, white hair, horns"],
    "nightingale": [r"nightingale (arknights)", "girl, blonde hair"],
    "warfarin": [r"warfarin (arknights)", "girl, white hair, horns"],
    "ptilopsis": [r"ptilopsis (arknights)", "girl, white hair"],

    # ===== 辅助 / 特种 =====
    "angelina": [r"angelina (arknights)", "girl, brown hair"],
    "magallan": [r"magallan (arknights)", "girl, black hair"],
    "glaucus": [r"glaucus (arknights)", "girl, blue hair"],
    "weedy": [r"weedy (arknights)", "girl, grey hair"],
    "projekt red": [r"projekt red (arknights)", "girl, grey hair, animal ears"],

    # ===== 深海阵营 =====
    "gladiia": [r"gladiia (arknights)", "woman, white hair"],
    "andreana": [r"andreana (arknights)", "girl, purple hair"],

    # ===== 萨卡兹 / 魔族 =====
    "surtr": [r"surtr (arknights)", "girl, red hair, horns"],
    "mudrock": [r"mudrock (arknights)", "woman, grey hair, horns"],
    "horn": [r"horn (arknights)", "woman, blonde hair"],

    # ===== 其他高人气 =====
    "texas": [r"texas (arknights)", "girl, black hair, animal ears"],
    "lappland": [r"lappland (arknights)", "girl, white hair, animal ears"],
    "mostima": [r"mostima (arknights)", "woman, blue hair, horns"],
    "skadi alter": [r"skadi the corrupting heart (arknights)", "girl, white hair"],
    "specter alter": [r"specter the unchained (arknights)", "girl, white hair"],

    # ===== 男角色（只留常见）=====
    "silverash": [r"silverash (arknights)", "man, white hair"],
    "thorns": [r"thorns (arknights)", "man, dark hair"],
    "mountain": [r"mountain (arknights)", "man, brown hair"],
    "executor": [r"executor (arknights)", "man, blonde hair"],

    

}
endfield_character = {
    "endministrator": [r"endministrator (arknights)", "girl, black hair"],
    "female endministrator": [r"female endministrator (arknights)", "girl, black hair"],

    "male endministrator": [r"endministrator (arknights), male endministrator (arknights)", "boy, black hair"],
    "perlica": [r"perlica (arknights)", "girl, white hair"],
    "yvonne": [r"yvonne (arknights)", "girl, red hair"],
    "gilberta": [r"gilberta (arknights)", "girl, brown hair"],
    "chen qianyu": [r"chen qianyu (arknights)", "girl, black hair, horns"],
    "laevatain": [r"red hair, horns", "girl, red hair", "reference\\endfield\\laevatain.png"],
    "bieli": [r"blue hair, horns", "girl, blue hair", "reference\\endfield\\bieli.png"],
    "ardelia": [r"brown hair, sheep girl, drill ponytail", "girl, brown hair", "reference\\endfield\\ardelia.png"],
    "tangtang": [r"black hair, tiger girl, animal ears", "girl, black hair, animal ears", "reference\\endfield\\tangtang.png"],
    "zhuang fangyi": [r"black hair, dragon girl, horns", "girl, black hair, horns", "reference\\endfield\\zhuang fangyi.png"],
    "rossi": [r"blonde hair, wolf girl, animal ears, hoodie", "girl, blonde hair, animal ears", "reference\\endfield\\rossi.png"],


}
honkai3rd_character = {
    "captain": [r"captain (honkai impact), red hair", "boy, red hair"],
    "kanchou": [r"captain (honkai impact), red hair", "boy, red hair"],
    "chu mo": [r"captain (honkai impact), red hair", "boy, red hair"],
    "chumo": [r"captain (honkai impact), red hair", "boy, red hair"],
    "seele vollerei": [r"seele vollerei", "girl, purple hair"],
    "seele": [r"seele vollerei (herrscher of rebirth)", "girl, purple hair"],
    "swallowtail seele": [r"seele vollerei (swallowtail phantasm)", "girl, purple hair"],
    "elysia": [r"elysia (honkai impact)", "girl, pink hair"],
    "rita": [r"rita rossweisse", "girl, blonde hair"],
    "rita rossweisse": [r"rita rossweisse", "girl, blonde hair"],
    "theresa": [r"theresa apocalypse ", "girl, white hair"],
    "theresa apocalypse": [r"theresa apocalypse ", "girl, white hair"],
    "murata himeko": [r"murata himeko", "girl, red hair"],
    "fu hua": [r"fu hua", "girl, grey hair, blue eyes"],
    "herrscher of sentience": [r"herrscher of sentience ", "girl, grey hair, red eyes, jewelry "],
    "kiana kaslana": [r"kiana kaslana", "girl, white hair"],
    "kiana": [r"kiana kaslana", "girl, white hair"],
    "griseo": [r"griseo", "girl, blue hair"],
    "aponia": [r"aponia (honkai impact)", "girl, blonde hair"],
    "yae sakura": [r"yae sakura", "girl, pink hair"],
    "pardofelis": [r"pardofelis", "girl, brown hair"],
    "mobius": [r"mobius (honkai impact)", "girl, green hair"],
    "homu": [r"homu (honkai impact)", "toy, rabbit toy"],
    "homei": [r"homei (honkai impact)", "toy, rabbit toy"],
    "luna kindred": [r"theresa apocalypse (luna kindred) ", "girl, white hair, red flower hair ornament"],
    "starlit": [r"zhuge kongming (honkai impact)", "girl, white hair"],
    "sirin": [r"sirin (magic academy uniform)", "girl, purple hair"],
    "kevin": [r"kevin kaslana", "boy, white hair"],
    "mei": [r"raiden mei (herrscher of thunder) ", "girl, purple hair"],
    "raiden mei": [r"raiden mei (herrscher of thunder) ", "girl, purple hair"],
    "kallen": [r"kallen kaslana", "girl, white hair"],
    "fallen rosemary": [r"rita rossweisse (fallen rosemary)", "girl, beown hair"],
    "ai-chan": [r"ai-chan (honkai impact)", "girl, green hair"],
    "eden": [r" eden (honkai impact)", "girl, red hair"],
    "bunny": [r" bronya zaychik (haxxor bunny)", "girl, grey hair, hoodie"],
    "haxxor bunny": [r" bronya zaychik (haxxor bunny)", "girl, grey hair, hoodie"],
    "durandal": [r"durandal (honkai impact)", "girl, golden hair"],
    "murata himeko": [r"murata himeko", "girl, red hair"],
    "himeko": [r"murata himeko", "girl, red hair"],
    # "bronya zaychik": [r"bronya zaychik (herrscher of reason)", "girl, grey hair"],
    # "bronya": [r"bronya zaychik (herrscher of reason)", "girl, grey hair"],
    "bronya zaychik": [r"bronya zaychik (silverwing: n-ex) ", "girl, grey hair"],
    "bronya": [r"bronya zaychik (silverwing: n-ex) ", "girl, grey hair"],
    
}

bluearchive_character = {
    "sensei": [r"sensei (blue archive), black hair", "boy, black hair"],
    "serika": [r"serika (blue archive)", "girl, black hair"],
    "serina": [r"serika (blue archive)", "girl, black hair"],
    "seia": [r"seia (blue archive)", "girl, blonde hair"],
    "hoshino": [r"hoshino (blue archive)", "girl, pink hair"],
    "yuuka": [r"yuuka (blue archive)", "girl, purple hair"],


}

anime_char = {
    "gotoh hitori": [r"gotoh hitori", "girl, pink hair"],
    "bocchi": [r"gotoh hitori", "girl, pink hair"],
    "gotoh futari": [r"gotoh futari", "girl, pink hair"],
    "kita ikuyo": [r"kita ikuyo", "girl, red hair"],
    "kita": [r"kita ikuyo", "girl, red hair"],
    "yamada ryou": [r"yamada ryou", "girl, blue hair"],
    "ijichi nijika": [r"ijichi nijika", "girl, blonde hair"],
    "nijika": [r"ijichi nijika", "girl, blonde hair"],

    "hirasawa yui": [r"hirasawa yui", "girl, brown hair"],
    "akiyama mio": [r"akiyama mio", "girl, black hair"],
    "tainaka ritsu": [r"tainaka ritsu", "girl, brown hair"],
    "kotobuki tsumugi": [r"kotobuki tsumugi", "girl, blonde hair"],
    "nakano azusa": [r"nakano azusa", "girl, black hair"],
    "hirasawa ui": [r"hirasawa ui", "girl, brown hair"],
    "yamanaka sawako": [r"yamanaka sawako", "girl, brown hair"],

    "nishikigi chisato": [r"nishikigi chisato", "girl, blonde hair"],
    "chisato": [r"nishikigi chisato", "girl, blonde hair"],
    "inoue takina": [r"inoue takina", "girl, black hair"],
    "takina": [r"inoue takina", "girl, black hair"],
    "nakahara mizuki": [r"nakahara mizuki", "girl, brown hair"],
    "mizuki": [r"nakahara mizuki", "girl, brown hair"],
    "kurumi": [r"kurumi (lycoris recoil)", "girl, blonde hair"],
    
}



# 3. 其他角色 (Other Characters)
other_char = {

    "main boy": [r"black hair, short hair", "boy, black hair"],
    "laffey": [r"laffey (azur lane), ", "girl, white hair"],

    "aizawa yuuichi": [r"aizawa yuuichi", "boy, brown hair"],
    "hinatsuru ai": [r"hinatsuru ai", "girl, brown hair"],
    "kuzuryuu yaichi": [r"kuzuryuu yaichi", "boy, brown hair"],
    "sora ginko": [r"sora ginko", "girl, blue hair"],

}

BASE_CHARACTER_MAP = {**genshin_char, **starrail_char, **zzz_character, **mc_character,
                      **arknights_character, **endfield_character, **honkai3rd_character,
                      **bluearchive_character, **anime_char, **other_char}

# Backward-compat alias: preset-only snapshot. Do not mutate in request path.
character_map = dict(BASE_CHARACTER_MAP)


def get_character_map(custom_data: dict | None = None) -> dict:
    """返回本次请求可用的角色映射（预设 + 可选用户自定义），不修改全局状态。"""
    merged = dict(BASE_CHARACTER_MAP)
    if custom_data:
        merged.update(custom_data)
    return merged


def reload_custom(custom_data: dict | None = None, inplace: bool = False) -> dict:
    """兼容旧接口：返回合并后的角色映射。

    默认不修改全局状态；仅在 inplace=True 时才会就地更新全局 character_map。
    """
    merged = get_character_map(custom_data)
    if inplace:
        character_map.clear()
        character_map.update(merged)
    return merged


def replace_tags_prompt(text: str, cmap: dict | None = None) -> str:
    """
    替换文本中的尖括号部分为character_map中数组的第一个值（用于prompt）
    例如: <furina> -> furina (genshin impact)
    """
    current_map = cmap or character_map

    def replace_match(match):
        key = match.group(1)
        lookup_key = key.replace("_", " ")
        if lookup_key in current_map:
            return current_map[lookup_key][0]
        return f"<{key}>"
    
    return re.sub(r'<([^>]+)>', replace_match, text)

def replace_tags_character(text: str, cmap: dict | None = None) -> tuple[str, str | None]:
    """
    替换文本中的尖括号部分，返回替换后的文本和可能的引用图片路径。
    如果 character_map 中存在第三个元素，则返回该路径。
    """
    reference = None
    current_map = cmap or character_map

    def replace_match(match):
        nonlocal reference
        key = match.group(1)
        lookup_key = key.replace("_", " ")
        if lookup_key in current_map:
            val = current_map[lookup_key]
            if len(val) >= 3:
                reference = val[2]
            return val[0]
        return f"<{key}>"
    
    new_text = re.sub(r'<([^>]+)>', replace_match, text)
    return new_text, reference

def replace_tags_speaker(text: str, cmap: dict | None = None) -> str:
    """
    替换文本中的尖括号部分为character_map中数组的第二个值（用于speaker）
    例如: <furina> -> girl, white hair
    """
    current_map = cmap or character_map

    def replace_match(match):
        key = match.group(1)
        lookup_key = key.replace("_", " ")
        if lookup_key in current_map:
            return current_map[lookup_key][1]
        return f"<{key}>"

    return re.sub(r'<([^>]+)>', replace_match, text)


# 4. BGM 标签映射 (Background Music Tag Map)
BGM_DIR = BASE_PATH / "bgm"

# 氛围：宁静，抒情，欢快，激昂
bgm_map: dict[str, list[str]] = {
    "原神/HOYO-MiX - 仰月所昭之路 The Path That the Moon Reveals.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 冀求之意 Desire's Intent.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 冬霰锐冽 Keen as Winter Hail.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 凶妄的夙念 An Obsession Unriven.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 切心的渴求 A Thirst That Cuts.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 列岛的晓风 Dawn Breeze of Lempoinen.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 初焙的恬脆 Fresh Baked Egg Rolls.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 初霜涓涟 Whimpering Morningfrost.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 匿行潜踪 Leaving No Trace.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 千湖与月的秘径 Kuunsilta of Thousand Lakes.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 升于陨圮 Raised on Fallen Meteorites.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 向晚的丘甸 Fields After Dusk.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 咏月者的谎言 A Lie of Aila.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 哀茕如霭 Grief Spreading Like Haze.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 圣仪默示之所 Hint From the Moonshadow.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 壤土下的安居 Cozy Home Underground.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 夕景伴归途 Rising When Night Falls.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 夜阑安暇时 At Ease Near Night's End.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 如霞的盐沼 Rosy Marshland.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 实力碾鸭 Duckle 'em Down!.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 寒涌的伫望 Foresighting From the Frigid Shore.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 岬石与细浪之舞 Hopak of Cape and Wave.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 巨炮铿轰 The Great Cannon Thundering.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 幽芒驻息 Where the Wandering Ones Rest.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 惶悚的灼念 Dreadful Darkness Closing In.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 愁绪谧息 Sorrows Calmed.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 戒禁之域 The Forbidding Ground.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 新月的摇篮曲（其一）：伴月同眠 Lullaby of the New Moon (I) Somnias a Luna.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 新月的摇篮曲（其三）：眉间落英 Lullaby of the New Moon (III) Petala ceciderunt.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 新月的摇篮曲（其二）：宵晖下的笑颜 Lullaby of the New Moon (II) Lucens ut risus.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 晚祷的铃歌 Dzwony na nieszpory.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 暂刻的时光 A Borrowed Hour.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 暮雨的沫痕 Vestige of Hurtling Foam.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 曦光所引 Led by Lucent GuIda Elinance.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 未然的乐土 Half-Finished Heaven.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 未相逢的再遇 A Remeet of First Meetings.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 束光似水 Light Shines Through Fingers as a Silver Stream.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 柜上的淑女 A Sitting on a Gate.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 死荫的黯色 The Perilous Fog.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 永夜与破晓的誓刃 To Light the Aeon Dark.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 浮槃与蓝穹的秘话 Shetau of Tulaytullah and Pushpavatika.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 海舶归港 Homecoming to Port.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 海蚀的幽廊 Sea-Gnawed Hollow.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 涉行之刻 Wading in Hazy Light.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 淑女的证明，或数秘的交谊舞 La preuve d'une demoiselle, ou le bal de la numerologie.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 深岩隐歌 Secrets Cast in a Deep Cave.mp3": ["原神", "宁静"],
"原神/HOYO-MiX - 深黯与幽火 Luchnos en toi Skotei.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 清辉下的参礼 Rite Beneath the Radiance.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 游步欣愉 Gladsome Ramble.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 湖色映蓝 Lakelight Turquoise.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 滨海拂风 Whirling Out and Over.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 澈夜低徊 Wandering Through the Starry Night.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 灾焰忽起 Fire and Shadow.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 煦寒的惦念 Warm Remembrance.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 牵梦的别绪 Dreams of Joy Departed.mp3": ["原神", "平静"],
    "原神/HOYO-MiX - 瓦砾与喧声 Ruinous Clamor.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 白夜洇润 Unfurling Night.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 白昼将临 Armor of Light.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 白桦与清水之梦 Dream of Birch and Pellucid Water.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 皎亮的边野 The Bright Frontier Land.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 皎晶澄凝 Dalliance of Crystal Light.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 石下暗涌 Darkness Surges Beneath the Stone.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 空待的重逢 Votum Awaited in Vain.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 繁沸之港 The Bustling Port Market.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 纤辉之纺 The Gleaming Thread.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 绿丘焕然 A Green Hill Remade.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 自外而至 From Beyond.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 船歌优稳 Sea Shanties Resounding.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 苍银的圣咒 Syntyloitsut of Koitar.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 苔骨的寒籁 Where the Cricket Sings.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 荒落的祀歌 Vessel for Prayer.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 荩草之途 Loafing on the Grass.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 萦思随白帆 Sails Set With Eagerness.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 蒙泽的遐裔 Ancient Heirs of Grace.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 诗境所蕴的旧事 Old Tales Inscribed in Verse.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 诡影蛰动 What Sleeps in Shadow Now Wakes.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 谧宁如镜水 Reflections in a Timeless Calm.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 近月赞咏 Hymn to the Moon.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 述往心的霜盏 Tells of the Frost-Lamp in One's Heart.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 遥月孤清 The Distant Moon Sits Alone.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 铁铸的洪流 The Iron-Cast Torrent.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 银鸥的回旋 Tourdion of Silver Seagulls.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 锤砧间的音符 Notes From Striking the Anvil.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 闲饮酣适 A Carefree Cup.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 雨月夜想 Mayskaya Noch'.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 雪浪驰逐 Straight Through the Snowtide.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 雾乡哀语 Sariola's Threnody.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 静伫的海峤 The Still Sea-Cliff.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 风中的军垒 The Redoubt Amidst the Frigid Wind.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 风挟的预兆 Omens Brought On the Wind.mp3": ["原神", "欢快"],
    "原神/HOYO-MiX - 飘曳的眠梦 The Swinging Motion of the Hulls.mp3": ["原神", "抒情"],
    "原神/HOYO-MiX - 飞觥走斝 Terms of Accord.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 驻息的孤影 The Solitary Silhouette.mp3": ["原神", "激昂"],
    "原神/HOYO-MiX - 鳞光倏烁 Shimmering Water Like Flickering Souls.mp3": ["原神", "宁静"],
    "原神/HOYO-MiX - 鼓荡的街镇 The Roiling Streets.mp3": ["原神", "宁静"],
    "崩三/HOYO-MiX - 一棹长天渺 A Lone Oar Into the Vast Horizon (1).mp3": ["崩三", "宁静"],
"崩三/HOYO-MiX - 不可思议的奇迹 An Incredible Miracle.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 不死的悲愿 Undying Tragic Wish.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 不要迷失 Don't Get Lost (1).mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 不要迷失 Don't Get Lost.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 不要遗忘 Don't Forget (1).mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 不要遗忘 Don't Forget.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 与你的心跳回忆 Heart-Throbbing Memories With You.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 与你相遇 Meeting You.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 与你重逢 Reunited With You.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 乐园小步舞 Paradise Minuet.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 于悠远的时光中 In the Distant Time.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 于烈火中倾颓 Collapse in Flames (1).mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 于烈火中倾颓 Collapse in Flames.mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 倾心浪漫曲 Romantic Ballade.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 喧鼓映佳岁 Loud Drums Welcome a Fair Year (1).mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 喧鼓映佳岁 Loud Drums Welcome a Fair Year.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 因逝去而不朽 Permanence Through Death.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 土拨鼠之歌 Groundhog's Song.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 在热情的阳光下 In the Passionate Sun.mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 在神明的庭院中 In the God's Courtyard.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 妖精小姐的魔法邀约 Miss Elf's Magical Invitation（伴奏）.mp3": ["崩三", "宁静"],
"崩三/HOYO-MiX - 心愿绽放之时 When Wishes Bloom.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 心灵休憩之所 A Haven for the Soul.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 心狱囚笼 Prison of the Heart.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 戍守黎明的大冒险 The Great Adventure of Dawn's Watch.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 手植星辰之日 The Day Stars Were Planted.mp3": ["崩三", "宁静"],
"崩三/HOYO-MiX - 撕裂无光之夜 Rend the Lightless Night.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 放逐哀惧之地 Land of Banished Sorrow and Fear.mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 放逐死亡的阴翳 Banish the Shade of Death.mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 日冕之城 The City Crowned By Sun (1).mp3": ["崩三", "欢快"],
    "崩三/HOYO-MiX - 日冕之城 The City Crowned By Sun.mp3": ["崩三", "欢快"],
    "崩三/HOYO-MiX - 旧日墟烟 Ruins of Yesterday.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 栖息在叶片上的愿望 Wishes Resting on Leaves.mp3": ["崩三", "欢快"],
    "崩三/HOYO-MiX - 欢闹吉祥星 Lively Auspicious Star (1).mp3": ["崩三", "欢快"],
"崩三/HOYO-MiX - 永生之英雄传说 Legend of the Immortal Hero.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 沐浴永恒的泉水 Bathe in the Spring of Eternity.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 泯灭之影 Shadow of Oblivion.mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 深瞑漩涡 Deep Dark Vortex (1).mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 深瞑漩涡 Deep Dark Vortex.mp3": ["崩三", "激昂"],
    "崩三/HOYO-MiX - 漂漂亮亮的回忆 Pretty Memories.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 畏惧与怀念的一切 All That We Fear and Long For.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 索取不朽的恩惠 Seek the Grace of Permanence.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 约定的决胜局 The Promised Final Match.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 花与爱的盛大谢幕 The Grand Finale of Flowers and Love.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 诞生于爱的故事 A Story Born from Love.mp3": ["崩三", "抒情"],
    "崩三/HOYO-MiX - 请慎重考虑并回答 Please Think Carefully and Answer.mp3": ["崩三", "宁静"],
    "崩三/HOYO-MiX - 骑士的誓言 Knight's Oath.mp3": ["崩三", "抒情"],
    "崩三/宴宁,HOYO-MiX - 妖精小姐的魔法邀约 Miss Elf's Magical Invitation.mp3": ["崩三", "宁静"],
    "崩铁/HOYO-MiX - NAME == 隐德来希 NAME == Entelechy.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 一曲终了 The Final Note.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 一页永恒 An Eternal Page.mp3": ["崩铁", "抒情"],
"崩铁/HOYO-MiX - 为往昔而行 A Journey for the Past.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 举手之劳 Piece of Cake.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 于长夜重返大地 Back to Earth in Evernight.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 亲爱的三月七 Dear March 7th.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 以全世之名 In the Name of All Worlds.mp3": ["崩铁", "宁静"],
"崩铁/HOYO-MiX - 何罪之有 The Sin of Pride.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 再创世 Era Nova.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 再度和你 With You Once More.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 再见，昔涟 Farewell, Cyrene.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 凄焰 Infernal Blaze.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 凝固的浪花 Frozen Tides.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 剑冢 Tomb of Blades.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 因为太阳将要毁伤 For the Sun is Set to Die.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 圣林 Sacred Grove.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 在黎明升起时坠落 The Fall at Dawn's Rise.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 天黑请闭眼 Night Falls, Everyone, Close Your Eyes.mp3": ["崩铁", "抒情"],
"崩铁/HOYO-MiX - 宁神长梦 Tranquil Dream.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 帷幕视窗 The Looming Curtains.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 开拓者 Trailblazer.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 归处 Home.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 征服者的思忖 Conqueror's Contemplation.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 微光小调 Starlight Serenade.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 心忆 Remembrance of the Heart.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 心灵 Mind and Soul.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 成为昨日的明天 As Tomorrow Became Yesterday.mp3": ["崩铁", "宁静"],
"崩铁/HOYO-MiX - 拍摄进行中 Filming in Progress.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 故事之外：第8场 Exotale Scene 8.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 无名的疗愈 Nameless Healing.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 无瑕金血 Flawless Ichor.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 日冕 Coronal Radiance.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 时隙攻防 Clash of Time Rift.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 明日之约 Promise of Tomorrow.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 有关星空的寓言集•其二 Fables About the Stars Part 2.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 有求必应 Always Here to Help.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 泡沫之下 Beneath the Bubbles.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 洄游的希望 Migratory Hope.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 流淌的思念 Flowing Memories.mp3": ["崩铁", "抒情"],
"崩铁/HOYO-MiX - 海的女儿 Daughter of the Sea.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 深爱的世界 A World of Deep Love.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 深黑蔓延时 When Darkness Spreads.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 火尽薪传 Passing the Torch.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 烧尽神国之火 Immolation of the Heavens.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 病毒 Virus.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 相位偏移 Phase Shift.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 相见『很』晚 A Long 'Fated' Meeting.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 矩阵 Matrix.mp3": ["崩铁", "宁静"],
"崩铁/HOYO-MiX - 神话公理 Mythical Axiom.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 秘榭曲谣 Elysiae Melody.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 第十三矢量 Vector Thirteen.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 缓冲区 Buffer Zone.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 缔造明日 Forging Tomorrow.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 致世界 To the World.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 苦难汇聚成河 Agony Converging into River.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 蜃楼 Mirage.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 记忆是梦的开场白 Memories are the Prelude to Dreams.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 讴歌苍翠 Ode of the Verdant.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 跋涉 Trek.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 路漫长夜 The Long Road Through Evernight.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 迷境 Maze.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 遗恨蜃景 Mirage of Regrets.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 酣生梦宴 Sweet Dreams and Feasts.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 陌颜之人 Face of a Stranger.mp3": ["崩铁", "宁静"],
    "崩铁/HOYO-MiX - 风仍温暖时 When The Wind Was Warm.mp3": ["崩铁", "激昂"],
    "崩铁/HOYO-MiX - 黄金色祝愿 Golden Desires.mp3": ["崩铁", "抒情"],
    "崩铁/HOYO-MiX - 龙鸣霄壤 Echoes of Dragon.mp3": ["崩铁", "宁静"],
    "未分类/Angel City Chorale,Christopher Tin - Sogno di Volare (“The Dream of Flight”).mp3": ["史诗", "合唱"],
    "未分类/AURORA,HOYO-MiX - 挪德卡莱 Nod-Krai.mp3": ["原神", "挪德卡莱"],
    "未分类/Bandari - Childhood Memory.mp3": ["轻音乐"],
    "未分类/Coldplay - Viva La Vida.mp3": ["欧美", "激昂"],
    "未分类/Defrix - Walking In the Sun (Defrix Remix).mp3": ["电子", "土味"],
    "未分类/fhána - 青空のラプソディ.mp3": ["日语", "青春"],
    "未分类/Glenn Stafford, 星际争霸, Blizzard Entertainment - 天堂之魔.mp3": ["游戏", "史诗"],
    "未分类/Goose house - 光るなら.mp3": ["日语", "青春"],
    "未分类/Guiano, ヰ世界情緒 - 月 feat. ヰ世界情緒.mp3": ["日语", "抒情"],
    "未分类/halyosy, りぶ, そらる, ろん, Reol, 弟の姉, 上北健, しゃけみー - Connecting.mp3": ["日语", "热血"],
    "未分类/Hanser, 泠鸢yousa, 祖娅纳惜, 鹿乃 - 吉祥话.mp3": ["华语", "二次元"],
    "未分类/Hanser,YUKIri - 病名为爱（病名は愛だった）（Cover リン&レン）.mp3": ["未分类", "宁静"],
    "未分类/Hanser,三无Marblue - summertime.mp3": ["二次元"],
    "未分类/HOYO-MiX - 炽火之舞 A Dance in Fire.mp3": ["原神", "纳塔"],
    "未分类/Jason Hayes,Tracy Bush,Derek Duke - Echoes(Exclusive Track).mp3": ["游戏", "史诗"],
    "未分类/KBShinya,Hanser - 失眠飞行.mp3": ["华语", "二次元"],
    "未分类/Lollipop, Subside - Batte forte (Subside Extended Remix).mp3": ["电子", "土味"],
    "未分类/Ludovico Einaudi - Experience.mp3": ["纯音乐", "宁静"],
    "未分类/MAISONdes, 花譜, ツミキ - トウキョウ・シャンディ・ランデヴ feat. 花譜, ツミキ.mp3": ["未分类", "宁静"],
    "未分类/Maksim Mrvica - Croatian Rhapsody.mp3": ["纯音乐", "激昂"],
    "未分类/nano.RIPE - こだまことだま.mp3": ["日语", "青春"],
    "未分类/nano.RIPE - なないろびより.mp3": ["日语", "日常"],
    "未分类/RADWIMPS, 十明 - すずめ feat.十明.mp3": ["日语", "宁静"],
    "未分类/Rick Astley - Never Gonna Give You Up.mp3": ["欧美", "怀旧"],
    "未分类/Ted Reedy, Diablo, Blizzard Entertainment - 基兰岱.mp3": ["游戏", "暗黑"],
    "未分类/Vitas - THE STAR.mp3": ["欧美", "激昂"],
    "未分类/Wiz Khalifa, Charlie Puth - See You Again.mp3": ["欧美", "宁静"],
    "未分类/YOASOBI - 群青.mp3": ["日语", "抒情"],
    "未分类/ちぃむdmp☆ - 千本桜.mp3": ["日语", "热血"],
    "未分类/つじあやの - 風になる.mp3": ["日语", "治愈"],
    "未分类/テゴマス - 猫中毒.mp3": ["日语"],
    "未分类/ナユタン星人, 初音ミク - 太陽系デスコ.mp3": ["日语", "激昂"],
    "未分类/ワルキューレ - いけないボーダーライン.mp3": ["日语", "激昂"],
    "未分类/三无Marblue - 花月成双.mp3": ["华语", "二次元"],
    "未分类/三无Marblue,Hanser - 惊鹊（翻自 海伊、星尘Minus）.mp3": ["华语", "古风"],
    "未分类/上坂すみれ - 恋する図形(cubic futurismo).mp3": ["日语", "激昂"],
    "未分类/中島みゆき - ヘッドライト・テールライト.mp3": ["日语", "抒情"],
    "未分类/久石譲 - The Sun Also Rises.mp3": ["纯音乐", "壮阔"],
    "未分类/久石譲 - 塚森の大樹.mp3": ["纯音乐", "宁静"],
    "未分类/久石譲 - 海の見える街.mp3": ["纯音乐", "怀旧"],
    "未分类/乐正绫, 泠鸢yousa, 茶理理, Hanser, 三无Marblue - 千里邀月.mp3": ["华语", "二次元"],
    "未分类/井口裕香 - 白金ディスコ.mp3": ["日语", "激昂"],
    "未分类/任贤齐 - 伤心太平洋.mp3": ["华语", "怀旧"],
    "未分类/佐咲紗花 - Zzz.mp3": ["日语", "抒情"],
    "未分类/佐咲紗花 - 勇気一つを友にして.mp3": ["日语", "励志"],
    "未分类/兰音Reine - 人间万朵红.mp3": ["未分类", "宁静"],
    "未分类/兰音Reine - 小雨.mp3": ["二次元"],
    "未分类/兰音Reine - 花亦山（cover：音阙诗听）.mp3": ["华语", "二次元"],
    "未分类/兰音Reine - 鱼跃而上.mp3": ["未分类", "欢快"],
    "未分类/双笙（陈元汐） - 心做し.mp3": ["华语", "治愈"],
    "未分类/名塚佳織,小岩井ことり,福圓美里 - 姉妹ライフトーキング.mp3": ["日语", "日常"],
    "未分类/告五人 - 带我去找夜生活.mp3": ["华语", "抒情"],
    "未分类/周深 - Rubia.mp3": ["华语", "抒情"],
    "未分类/周深 - 千千阙歌 (Live).mp3": ["华语", "怀旧"],
    "未分类/富樫美铃 - 日常のまち.mp3": ["日语", "日常"],
    "未分类/小倉唯 - Clear Morning.mp3": ["抒情", "游戏"],
    "未分类/小倉唯 - 回レ！雪月花 (小紫Ver.).mp3": ["日语", "热血"],
    "未分类/山岡晃 - Promise.mp3": ["游戏", "氛围"],
    "未分类/张韶涵, 王赫野 - 篇章.mp3": ["华语", "抒情"],
    "未分类/张韶涵,HOYO-MiX - 昔涟.mp3": ["崩铁", "抒情"],
    "未分类/本田晃弘, 伊藤翼 - 旅の始まり.mp3": ["游戏", "激昂"],
    "未分类/李佳璐 - 无法原谅.mp3": ["华语", "抒情"],
    "未分类/李克勤 - 红日.mp3": ["华语", "激昂"],
    "未分类/李如意 - 明天会更好（童声版）.mp3": ["华语", "励志"],
    "未分类/李尧音 - 深海回响.mp3": ["华语", "激昂"],
    "未分类/泠鸢yousa - 勾指起誓.mp3": ["二次元"],
    "未分类/泠鸢yousa - 神的随波逐流.mp3": ["二次元"],
    "未分类/泠鸢yousa, 音阙诗听 - 大喜.mp3": ["华语", "二次元"],
    "未分类/泠鸢yousa,Hanser,呆萌忆 - 悠哉日常~悠哉~悠哉.mp3": ["二次元"],
    "未分类/浜渦正志 - サンレス水郷.mp3": ["游戏", "宁静"],
    "未分类/知更鸟,HOYO-MiX,Chevy - 希望有羽毛和翅膀.mp3": ["崩铁", "知更鸟"],
    "未分类/穆小泠 - 弹指醉.mp3": ["华语", "二次元"],
    "未分类/米白 - 横竖撇点折.mp3": ["华语", "二次元"],
    "未分类/結束バンド - なにが悪い.mp3": ["日语", "激昂"],
    "未分类/花玲, 张安琪, 沐霏 - 我不曾忘记.mp3": ["游戏", "宁静"],
    "未分类/花譜 - それを世界と言うんだね.mp3": ["日语", "抒情"],
    "未分类/茅野愛衣, 戸松遥, 早見沙織 - secret base ~君がくれたもの~ (10 years after Ver.).mp3": ["日语", "宁静"],
    "未分类/蔡健雅 - 红色高跟鞋.mp3": ["华语", "抒情"],
    "未分类/蔡健雅 - 被驯服的象.mp3": ["华语", "抒情"],
    "未分类/说说Crystal - 不问天.mp3": ["华语", "二次元"],
    "未分类/说说Crystal - 天知河.mp3": ["华语", "二次元"],
    "未分类/说说Crystal - 快乐手帐.mp3": ["华语", "二次元"],
    "未分类/说说Crystal - 昨日青空.mp3": ["二次元"],
    "未分类/说说Crystal - 桃华.mp3": ["华语", "二次元"],
    "未分类/说说Crystal - 流年如歌2022.mp3": ["华语", "二次元"],
    "未分类/谭维维, 梦幻西游 - 易燃易爆炸.mp3": ["华语", "激昂"],
    "未分类/郭采洁 - 我的未来式.mp3": ["华语", "抒情"],
    "未分类/阿肆 - 热爱105°C的你.mp3": ["华语", "抒情"],
    "未分类/青鸟飞鱼 - 此生不换.mp3": ["华语", "抒情"],
    "未分类/高橋李依, KOTONOHOUSE - Sprout.mp3": ["日语", "抒情"],
    "未分类/高橋李依,豊崎愛生 - Red Battle.mp3": ["日语", "战斗"],
    "未分类/鸣潮先约电台, xTR33x, Tarokiki - 永不结束的歌.mp3": ["鸣潮", "抒情"],
    "滨崎正志/浜渦正志 - Choose to Fight.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - FINAL FANTASY XIII ~誓い~.mp3": ["滨崎正志", "抒情"],
    "滨崎正志/浜渦正志 - FINAL FANTASY XIII プレリュード.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - FINAL FANTASY XIII~奇跡~.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - PSICOM.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - あの日の空.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - おまえの家はここだ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - つかのまの安息.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - アフロブルース.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - アルカキルティ大平原.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ウォーリーをさがせ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - エンディングロール.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - カウントダウン.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ガプラ樹林.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - グラン=パルスのルシ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ゲームオーバー.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - コクーンdeチョコボ~夢をみようよII~.mp3": ["滨崎正志", "抒情"],
    "滨崎正志/浜渦正志 - サッズのテーマ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - スノウのテーマ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - スーリヤ湖.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - セラのテーマ.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - ドレッドノート大爆進!.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - バトルリザルト.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - パルスdeチョコボ.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - ビルジ湖.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ファングのテーマ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ファンブラ・ノヴァ・クリスタリス.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - ホープのテーマ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ポンパ・サンクタ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ヤシャス山.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ライトニングのテーマ.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - ルシたちの想い.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - ルシの試練.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - ヴァニラのテーマ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 下界のファルシ.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - 偽りの饗宴.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 償い.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 優しい思い出.mp3": ["滨崎正志", "抒情"],
    "滨崎正志/浜渦正志 - 刻限.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 動乱のエデン.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 召喚獣.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 宿命への抗い.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 封鎖区画ハングドエッジ.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 希望なき闘争.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 帰るための戦い.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 帰郷.mp3": ["滨崎正志", "抒情"],
    "滨崎正志/浜渦正志 - 恩讐果て.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 悲深き希望.mp3": ["滨崎正志", "抒情"],
    "滨崎正志/浜渦正志 - 撃墜.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 果てなき疾走.mp3": ["滨崎正志", "激昂"],
"滨崎正志/浜渦正志 - 死闘.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 永遠の誓い.mp3": ["滨崎正志", "抒情"],
    "滨崎正志/浜渦正志 - 決意.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 父ちゃん奮闘だぁ!.mp3": ["滨崎正志", "欢快"],
    "滨崎正志/浜渦正志 - 生誕のレクイエム.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 異境大陸グラン=パルス.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 異跡.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 神秘.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 第13日.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - 継ぎゆく意志.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 緊迫.mp3": ["滨崎正志", "激昂"],
"滨崎正志/浜渦正志 - 脱出.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 色のない世界.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 見失った希望.mp3": ["滨崎正志", "抒情"],
    "滨崎正志/浜渦正志 - 逃げてもいいの.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 運命への反逆.mp3": ["滨崎正志", "激昂"],
    "滨崎正志/浜渦正志 - 遺棄領域ヴァイルピークス.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/浜渦正志 - 閃光.mp3": ["滨崎正志", "宁静"],
"滨崎正志/浜渦正志 - 騎兵隊のテーマ.mp3": ["滨崎正志", "宁静"],
    "滨崎正志/菅原纱由理（THE SxPLAY） - Eternal Love (Short Version).mp3": ["滨崎正志", "抒情"],
    "滨崎正志/菅原纱由理（THE SxPLAY） - 君がいるから.mp3": ["滨崎正志", "抒情"],
}

def get_bgm_paths(include_tags: list[str] | None = None,
                  exclude_tags: list[str] | None = None,
                  bmap: dict | None = None) -> list[Path]:
    """
    根据标签从bgm_map中筛选音乐文件路径。

    include_tags: 若提供，只保留至少命中其中一个标签的音乐
    exclude_tags: 若提供，剔除命中其中任意一个标签的音乐
    返回符合条件的音乐文件路径(Path对象)列表
    """
    current_map = bmap or bgm_map
    include_set = set(include_tags) if include_tags else None
    exclude_set = set(exclude_tags) if exclude_tags else None

    result = []
    for filename, tags in current_map.items():
        tag_set = set(tags)
        if include_set is not None and not (tag_set & include_set):
            continue
        if exclude_set is not None and (tag_set & exclude_set):
            continue
        result.append(BGM_DIR / filename)
    return result

